### PR TITLE
Convert from Python 2 to 3 & Enable Travis CI

### PR DESCRIPTION
**Pull request by ofuhrer**
The following changes are implemented in this PR:
- Basic conversion (without code cleanup) from Python 2 to 3.
- Travis CI integration (see https://travis-ci.com/VulcanClimateModeling/testsuite).

_Note 1: Due to lack of regression testing for some of the code and the scripts, not all functionality could be tested._

_Note 2: This PR is a pre-requisite for Travis integration, since Travis can not gracefully deal with a mixed codebase of Python 2 and 3, as is currently the case. Once it is in, we can enable regression testing on the C2SM-RCM repo._

### CODE REVIEW

**Comment by guydemorsier** [comment]
launch jenkins

**Review by guydemorsier — APPROVED** [review]
Great to leave python 2 behind!
I guess we need to do a test here first.
For some reasons kesch is offline. More later.

**Comment by guydemorsier** [comment]
Now the test has problems finding the built-in module configparser which is defined just below in testsuite.py

**Comment by ofuhrer** [comment]
I think you are still using Python2 in that case. ConfigParser was renamed configparser in py3 as far as I know.

**Comment by ofuhrer** [comment]
Maybe try adding a “which python; python —version” just before the testsuite.py is being called.

**Comment by guydemorsier** [comment]
That is possible, I will to add module load PE/17 python/3.6.2-gmvolf-17.02

**Comment by ofuhrer** [comment]
Also, there are dependencies that are formalized in requirements.txt. If you look at env.sh it shows you a file that can be sourced to setup the environment for running the testsuite.

**Comment by guydemorsier** [comment]
if [[ `hostname` == *"kesch"* ]]; then

Is probably not working!

**Comment by guydemorsier** [comment]
launch jenkins

**Comment by guydemorsier** [comment]
We managed to run the testsuite with python3 but then there are so many loaded modules (incl. mvapich2/2.2-gcc-5.4.0-2.26) that cosmo failed:
http://jenkins-mch.cscs.ch/job/testsuite/real_type=double,slave=kesch,target=gpu/60/
We probably need to have our own installation of python.
Happy birthday!

**Comment by lxavier** [comment]
Test with cosmo-org ok : http://jenkins-mch.cscs.ch/job/testsuite/real_type=double,slave=tsa,target=gpu/62/
Test failing with int2lm but this is already the case with master @guydemorsier for now I will deactivate int2lm in the testing but we should have a look

**Review by lxavier — APPROVED** [review]

**Comment by lxavier** [comment]
@ofuhrer sorry this has been long forgotten. Now we have a  proper python3 on tsa, so I changed all the testing to tsa.
How can we activate Travis ?

**Comment by ofuhrer** [comment]
Xavier,

In order to activate the regression tests on TravisCI, somebody need to activate Travis in the C2SM-RCM organization. I think I mailed Katie about it a while back. The README is currently still pointing to our branch of the testsuite and a broken link.

Cheers,
Oli

On Jun 2, 2020, at 1:09 PM, Xavier Lapillonne <notifications@github.com<mailto:notifications@github.com>> wrote:



Test with cosmo-org ok : http://jenkins-mch.cscs.ch/job/testsuite/real_type=double,slave=tsa,target=gpu/62/
Test failing with int2lm but this is already the case with master @guydemorsier<https://github.com/guydemorsier> for now I will deactivate int2lm in the testing but we should have a look

**Comment by guydemorsier** [comment]
@lxavier The testsuite is falling because it does not recognize the netcdf files but I checked that there are present and complete:
```
35:   [  MATCH   ] run_success_check.py
35:                  No netCDF output file found
35:   [   FAIL   ] existence_ncdf_out.sh
35:   [    OK    ] tolerance_check.py
35:   [  MATCH   ] output_tolerance_check.py
```
I think this should work with Python 3 or needs to be adapted.

**Pull request merged**
